<?php
/*
 * The MIT License
 *
 * Copyright 2020 João Rebelo.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
declare(strict_types=1);

namespace Rebelo\SaftPt\AuditFile;

/**
 * Country
 * @method static \Rebelo\SaftPt\AuditFile\Country DESCONHECIDO() 
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_AD()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_AE()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_AF()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_AG()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_AI()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_AL()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_AM()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_AO()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_AQ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_AR()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_AS()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_AT()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_AU()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_AW()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_AX()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_AZ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BA()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BB()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BD()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BE()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BF()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BG()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BH()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BI()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BJ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BL()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BM()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BN()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BO()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BQ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BR()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BS()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BT()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BV()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BW()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BY()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_BZ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_CA()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_CC()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_CD()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_CF()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_CG()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_CH()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_CI()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_CK()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_CL()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_CM()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_CN()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_CO()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_CR()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_CU()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_CV()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_CW()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_CX()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_CY()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_CZ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_DE()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_DJ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_DK()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_DM()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_DO()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_DZ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_EC()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_EE()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_EG()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_EH()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_ER()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_ES()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_ET()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_FI()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_FJ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_FK()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_FM()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_FO()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_FR()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_GA()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_GB()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_GD()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_GE()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_GF()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_GG()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_GH()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_GI()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_GL()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_GM()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_GN()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_GP()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_GQ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_GR()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_GS()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_GT()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_GU()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_GW()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_GY()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_HK()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_HM()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_HN()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_HR()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_HT()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_HU()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_ID()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_IE()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_IL()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_IM()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_IN()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_IO()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_IQ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_IR()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_IS()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_IT()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_JE()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_JM()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_JO()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_JP()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_KE()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_KG()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_KH()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_KI()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_KM()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_KN()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_KP()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_KR()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_KW()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_KY()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_KZ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_LA()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_LB()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_LC()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_LI()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_LK()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_LR()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_LS()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_LT()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_LU()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_LV()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_LY()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MA()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MC()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MD()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_ME()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MF()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MG()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MH()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MK()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_ML()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MM()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MN()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MO()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MP()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MQ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MR()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MS()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MT()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MU()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MV()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MW()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MX()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MY()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_MZ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_NA()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_NC()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_NE()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_NF()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_NG()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_NI()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_NL()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_NO()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_NP()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_NR()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_NU()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_NZ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_OM()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_PA()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_PE()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_PF()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_PG()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_PH()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_PK()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_PL()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_PM()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_PN()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_PR()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_PS()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_PT()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_PW()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_PY()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_QA()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_RE()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_RO()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_RS()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_RU()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_RW()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SA()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SB()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SC()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SD()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SE()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SG()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SH()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SI()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SJ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SK()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SL()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SM()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SN()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SO()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SR()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SS()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_ST()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SV()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SX()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SY()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_SZ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_TC()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_TD()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_TF()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_TG()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_TH()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_TJ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_TK()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_TL()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_TM()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_TN()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_TO()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_TR()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_TT()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_TV()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_TW()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_TZ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_UA()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_UG()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_UM()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_US()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_UY()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_UZ()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_VA()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_VC()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_VE()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_VG()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_VI()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_VN()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_VU()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_WF()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_WS()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_XK()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_YE()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_YT()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_ZA()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_ZM()
 * @method static \Rebelo\SaftPt\AuditFile\Country ISO_ZW()
 * 
 * @author João Rebelo
 */
class Country extends ACountry
{
    const DESCONHECIDO = "Desconhecido";

    /**
     *
     * @param string $value
     * @since 1.0.0
     */
    public function __construct(string $value)
    {
        parent::__construct($value);
    }

    /**
     *
     * Get Country as string
     *
     * @return string
     * @since 1.0.0
     */
    public function get(): string
    {
        return (string) parent::get();
    }
}
