#!/usr/bin/env php
<?php
/*
 * The MIT License
 *
 * Copyright 2020 João Rebelo.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

use Symfony\Component\Console\Application;

if (version_compare('7.4.0', PHP_VERSION, '>')) {
    fwrite(
        STDERR,
        sprintf(
            'This version of Saft4php is supported on PHP 7.4.'.PHP_EOL.
            'You are using PHP %s (%s).'.PHP_EOL, PHP_VERSION, PHP_BINARY
        )
    );
    die(1);
}

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'Europe/Lisbon');
}

foreach (array(__DIR__.'/../../autoload.php', __DIR__.'/../vendor/autoload.php',
__DIR__.'/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('PHP4SAFT_COMPOSER_INSTALL', $file);
        require_once $file;
        break;
    }
}

unset($file);

if (!defined('PHP4SAFT_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:'.PHP_EOL.PHP_EOL.
        '    composer install'.PHP_EOL.PHP_EOL.
        'You can learn all about Composer on https://getcomposer.org/.'.PHP_EOL
    );
    die(1);
}

$jsonStr = \file_get_contents(__DIR__.DIRECTORY_SEPARATOR."composer.json");

if ($jsonStr === false) {
    fwrite(
        STDERR, 'composer.json not readable:'.PHP_EOL.PHP_EOL
    );
    die(1);
}

$comp = \json_decode($jsonStr);
try {
    $application = new Application("saft4php", $comp->version);
    \Rebelo\SaftPt\Bin\Validate::$start = \time();
    $application->add(new \Rebelo\SaftPt\Bin\Validate());
    $application->run();
} catch (\Exception | \Error $e) {
    echo $e->getMessage();
    exit(1);
}

